#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER "${XNAT_DATASOURCE_USERNAME:-xnat}" WITH LOGIN PASSWORD '${XNAT_DATASOURCE_PASSWORD:-xnat}';
    CREATE DATABASE "${XNAT_DATASOURCE_NAME:-xnat}" OWNER "${XNAT_DATASOURCE_USERNAME:-xnat}";
EOSQL
