postgres:
  host: "postgres"
  port: "5432"
  username: "postgres"

  db: "testdb"

GraphDB:
    host: "postgres"
    port: "7200"
    repo: "protrait"

API:
    host: "postgres"
    port: "8666"

dvh-calculations:
  -
    P-LUNG:
      roi: "LUNG_L + LUNG_R"
  -
    MeanDoseIpsiLateralParotidGland:
      roi: "PAROTID_IPSI"
